name: Scrape COVID-19 Data
on:
  push:
    branches: 
      - master
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'
      
jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - name: Check out this repo
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Fetch latest data
      run: |-
        curl --location --request GET 'https://api.covid19api.com/dayone/country/germany' | jq . > docs/results.json
    - name: Commit and push if it changed
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        git commit -m "Latest data: ${timestamp}" || exit 0
        git push
